name: reactive_todo_app
description: A reactive todo app

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.2
  path_provider: ^2.0.9
  cupertino_icons: ^1.0.4
  equatable: ^2.0.3
  get_it: ^7.2.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  objectbox: ^4.0.2
  objectbox_flutter_libs: ^4.0.2
  test_rail_dart: ^0.0.4

dev_dependencies:
  test: ^1.17.12
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  bloc_test: ^9.0.3
  build_runner: ^2.1.8
  objectbox_generator: ^4.0.2
  change_app_package_name: ^1.3.0


objectbox:
  output_dir: core/object_box/

flutter:
  uses-material-design: true
